### ISSUE TITLE
Define Language Scope for 0.1

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/act#26]
This issues defines the language features in the scope of Act 0.1.

I'll start this comment with my suggestions, and we can update after discussions.

### Types

uint8, uint16, ... uint256, uint
int8, int16, ... int256, int
bytes1, ... bytes32
address
bool
string

### Sections

behaviour
interface
creates
invariants
case
storage
if
iff in range
iff
ensures

### Env vars

CALLER
CALLVALUE
CALLDEPTH
ORIGIN
BLOCKHASH
BLOCKNUMBER
DIFFICULTY
CHAINID
GASLIMIT
COINBASE
TIMESTAMP
THIS
NONCE

### Operators

`:=` (`creates` assignment)
`=>` implies or storage update
`==` eq
`=/=` neq
`>= <= > < ite`
`+ - * / ^`

**Comment by MrChico** [comment]
0.1 will only support Integer and Boolean types, no bytestrings

**Comment by MrChico** [comment]
also `if` is not supported right now, as it is mostly replaced by `cases`
