### ISSUE TITLE
Wrong treatment of `iff` conditions

### ISSUE THREAD

**Issue by MrChico** [ethereum/act#55]
Currently we assume the conjunction of the negation of `iff` conditions for fail specs, where we should be assuming the negation of their conjunction. Consequently, we can prove specs even though they contain redundant `iff` clauses:
```
behaviour add of SafeAdd
interface add(uint256 x, uint256 y)

iff in range uint256

    x + y

iff

    CALLVALUE == 0
    x == 1      /// <- REDUNDANT CONDITION

returns x + y
```

The spec above is provable against the `safemath` example in `hevm/pass/safemath`, but the fail spec should not be.

**Comment by MrChico** [comment]
Maybe this is a bad example because `safemath` times out now anyway. Here's a better one:
```solidity
contract A {
    uint x;
    function f() external returns (uint) {
        x = 2;
    }
}
```

```
behaviour constructor of A
interface constructor()

creates

  uint x := 0

behaviour f of A
interface f()

iff

  CALLVALUE == 0
  x == 1 // REDUNDANT CONDITION

storage

  x => 2
```

**Comment by leonardoalt** [comment]
Why is `x == 1` redundant? To me it just looks wrong

**Comment by MrChico** [comment]
Redundant in the sense that it is not a necessary condition for the spec to pass

**Comment by leonardoalt** [comment]
But in this case the spec is actually underspeced, isn't it?

**Comment by MrChico** [comment]
Not quite because `iff` should not introduce additional assumptions and restrict the domain of the spec, but actually specify that if any of the conditions are not met, there _must_ be a failure/revert. If this was an `if` or a `case`, you would be right.
