### ISSUE TITLE
Multiple state vars with the same name are accepted

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/act#70]
```
constructor of LValue
interface constructor()

creates

	uint x := 2
	bool x := false
```

This does not causes errors when `parse`/`type`.
If we add
```
invariants

	x >= 0
```
then `parse` fails with a type mismatch

**Comment by leonardoalt** [comment]
I'm not sure if this is the expected behavior, please close if so.

**Comment by MrChico** [comment]
This is definitely a bug imo
