### ISSUE TITLE
Internal error when type checking Real -> Int assignment

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/act#74]
```
constructor of LValue
interface constructor()

creates
	uint x := 2.5
```
->
```
act: internal error: infer type of:Zoom (AlexPn 67 5 20) (IntLit 2) (IntLit 5)
CallStack (from HasCallStack):
  error, called at Type.hs:363:10 in main:Type
```

**Comment by xwvvvvwx** [comment]
I think the error message will get nicer here once we implement support for the "zoom" dot syntax (e.g. `LValue.x`) for storage reads, we're running into the internal error here because some of the typechecking machinery around that language feature doesn't exist yet...
