### ISSUE TITLE
SMT: Remove Local Prestate for Constructor Queries

### ISSUE THREAD

**Issue by xwvvvvwx** [ethereum/act#91]
We currently generate both a pre and a post state for storage variables in constructor queries. This makes no sense for variables local to the contract since they don't exist at that point. 

We should rework the SMT backend so that no constructor prestate is generated.

**Comment by xwvvvvwx** [comment]
The following should probably be a type error:

```
constructor of C
interface constructor()

iff

    x == 7

creates

	uint x := 2
```

**Comment by leonardoalt** [comment]
A type error on `iff`?

**Comment by xwvvvvwx** [comment]
yes, as it is refering to the prestate of a storage variable that has not yet been created.

**Comment by leonardoalt** [comment]
Sounds good!

**Comment by kjekac** [comment]
Is this actually specific to the SMT backend? I agree that it should be a type error, but afaik the type checker lies sequentially before the backends. Dealing with it in the backends could certainly be done but it seems like a lot of unnecessary examination of the incoming `Constructor`s, which I believe we should just assume are correct if they passed type checking.
