### ISSUE TITLE
Introduce & enforce pre / post operators

### ISSUE THREAD

**Issue by d-xo** [ethereum/act#95]
After some thought and discussion in https://github.com/ethereum/act/issues/92, we have decided to introduce `pre` and `post` operators for storage references and also to enforce their use for all storage references.

While this is somewhat more verbose, it has the benefit of disambiguating the specification language, and should also help to simplify analysis based on the AST, since this metadata no longer has to be infered from the surrounding context (i.e. each storage ref in the AST will have a data field declaring whether it refers to the pre or post state).

**Comment by xwvvvvwx** [comment]
One thing that comes to mind, how should we interpret an invariant claim that has references to the storage prestate in the context of a constructor? The storage prestate does not exist in the constructor queries...

**Comment by leonardoalt** [comment]
How would the invariant refer to the pre state of the constructor? I'm not sure that should be available?

**Comment by xwvvvvwx** [comment]
Maybe `pre`/`post` operators don't make sense in invariant blocks at all? The invariant predicate is asserted over both the pre state and post state after all...

**Comment by leonardoalt** [comment]
Ahhh ok, I see what you mean. I think in general pre/post does make sense for invariants to disambiguate the semantics of state variable references.
I had forgotten that ofc the invariant also needs to be applied to the constructor, which means that there is a way to represent the pre state of the constructor. In that case, I would suggest that any `pre(x)` in the constructor means the zero-value of x's type.

**Comment by xwvvvvwx** [comment]
I don't see how we could construct the inductive step for an invariant query if the predicate contains both `pre` and `post` operators? We need to assert that the invariant holds over the prestate, and then also assert that it does not hold over the post state, so I think that we probably need to disallow `pre`/`post` in invariant blocks?

**Comment by MrChico** [comment]
I agree that pre/post doesn't make much sense in the invariant blocks

**Comment by leonardoalt** [comment]
Well, what if you want to state, for example, that a variable never decreases?

**Comment by leonardoalt** [comment]
> I don't see how we could construct the inductive step for an invariant query if the predicate contains both `pre` and `post` operators? We need to assert that the invariant holds over the prestate, and then also assert that it does not hold over the post state, meaning that storage references in the invariant block implicitly refer to both the pre and post state.

I don't really understand this sentence. The way the invariant queries are being generate already has pre and post versions for each state variable, right?
Why can't `pre(x) <= post(x)` be represented?

**Comment by leonardoalt** [comment]
Ah ok, got it now. We have been thinking of invariants in terms of a predicate over the "current" set of state vars, so yea, in that case I agree that pre/post doesn't make sense.

**Comment by MrChico** [comment]
> Ah ok, got it now. We have been thinking of invariants in terms of a predicate over the "current" set of state vars, so yea, in that case I agree that pre/post doesn't make sense.

Yeah, this is a simple first step at least – the language of invariants are formulas over the set of state vars, which must hold for every possible state of the contract.

If we introduce `pre` and `post`, we can now make claims of any pair subsequent of states of the contract. Naturally the initial state (i.e. the poststate of the constructor) becomes an edge case; is it a pre or post state? It must be a pre state because there is nothing preceding it and so otherwise `pre` would be undefined. So maybe I take back that it doesn't make much sense. But it's certainly a different level of expressivity, and we should decide which fragment we want to start with.

**Comment by leonardoalt** [comment]
I just realized that to me pre and post don't make sense as an invariant because an invariant is true for a state, not for a transition.

**Comment by kjekac** [comment]
I think it does make sense and suspect that I would like to see it implemented, because otherwise the postcondition `pre(x) <= post(x)` needs to be added once for every behavior, which seems unnecessarily verbose.

There is one gotcha with that approach though: if we take `pre(x) <= post(x)` as an invariant and it happens to be *false* for the first transition, that means that it always has to be false afterwards, which is likely not what we wanted to prove. 

Regardless I agree with Martin that this is a different beast that makes sense to tackle later. For now let's disallow it.

**Comment by leonardoalt** [comment]
I think this fits early discussions we had about `invariant` vs `property`, where an invariant has to be inductive over the functions and a property was a more general object.

**Comment by kjekac** [comment]
Ah nice, I was unaware of that! That does seem like a reasonable distinction at first glance.

**Comment by MrChico** [comment]
It's only dropped in the sense that for (inductive) `invariants`, we have a clear automatic proving strategy (induction + SMT), and for the more general `property`, it's not clear that SMT solvers will be able to handle it nor which strategy one should employ to solve it. So generally, the idea was that the more general `property` would be something that would likely need to be proven with coq or another proof assistant. But then why not write that property directly in coq anyway, after having generated the state transition from the spec? It would be a lot of overhead to recreate a DTT checker to just have a nice exporting to coq

**Comment by xwvvvvwx** [comment]
I think we will need some kind of cycle detection for storage assignments? if we allow `pre` / `post` without restriction then I think we can produce cyclic references?

```
constructor of Cycle
interface constructor(uint _a, uint _b)

creates

    uint a := _a
    uint b := _b

behaviour whoops of Cycle
interface whoops()

storage

    a => post(b)
    b => post(a)
```

**Comment by kjekac** [comment]
Do we have an opinion on stuff like this?

```
storage
  a => pre( stuff[ post(i) ].post(e) )
  b => post( stuff[ pre(j) ]).post(x)
```

Allow? Disallow? I'm leaning towards "disallow", basically saying that `pre` and `post` always distribute into the expression.

**Comment by kjekac** [comment]
I don't think `post` makes any sense to use in preconditions either? I mean I guess SMT wouldn't really care but for symbolic execution time actually flows forwards right? And also it would just feel really *weird* to see in a spec, imo.

So it's really only postconditions and storage rewrites which need `pre` and `post`? Or what do you guys think?

**Comment by xwvvvvwx** [comment]
I agree with both of the above :)

**Comment by leonardoalt** [comment]
Consensus:
- pre/post only exist in the post condition block
- pre/post are mandatory in the post condition block to refer to any variable

**Comment by kjekac** [comment]
What about `returns` blocks? Should `pre`/`post` be required there? Or will they always be `post`? Always `pre` sounds weird to me.

**Comment by kjekac** [comment]
>pre/post are mandatory in the post condition block to refer to any variable

Also fwiw I don't think we thought this through fully. Calldata vars never need to be pre/post, since they are immutable. Only storage refs need pre/post.

Please tell me if you disagree.

**Comment by kjekac** [comment]
Thanks for your likes but do you also have any comments on my first question? :)

**Comment by leonardoalt** [comment]
> What about `returns` blocks? Should `pre`/`post` be required there? Or will storage refs there always be `post`? To always have them `pre` sounds weird to me.

To me the `returns` block feels similar to the storage cases. I'm not sure `pre/post` fit there at all, but I agree that just saying `return x` means `pre(x)` is also weird. I guess here we do need either the `where` block or intermediate fresh variables or both.

**Comment by leonardoalt** [comment]
> Also fwiw I don't think we thought this through fully. Calldata vars never need to be pre/post, since they are immutable. Only storage refs need pre/post.
> 
> Please tell me if you disagree.

Right, my assumption was that we were talking about state variables only.

**Comment by xwvvvvwx** [comment]
I think requring `pre`/`post` in for storage refs in `returns` makes sense, since the returns is kind of a special postcondition on the contents of the EVM return buffer.

**Comment by kjekac** [comment]
> I think requring `pre`/`post` in for storage refs in `returns` makes sense, since the returns is kind of a special postcondition on the contents of the EVM return buffer.

Yeah I think I agree.
